version: '3.8'

services:
  rabbitmq:
    image: chainguard/rabbitmq:latest
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq:rw
    networks:
      - app-network

  opensearch-node:
    image: chainguard/opensearch:latest
    ports:
      - "9200:9200"   # REST API
      - "9300:9300"   # Internal communication
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      # Disable security and SSL for simplicity
      - plugins.security.disabled=true
      - plugins.security.ssl.transport.enabled=false
      - plugins.security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./opensearch_data:/usr/local/share/opensearch/data:rw
    networks:
      - app-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch-node
    networks:
      - app-network

  data-consumer:
    build:
      context: ./data-consumer
      dockerfile: Dockerfile
    depends_on:
      - opensearch-node
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  opensearch_data:
  rabbitmq_data:
